### ISSUE TITLE
Authentication on API

### ISSUE THREAD

**Issue by agger-magenta** [RedeMocambos/baobaxia#162]
All functions that change data should require authentication.

**Comment by agger-magenta** [comment]
I started looking into this. It's relatively easy to require authentication in the API. However, the client needs to handle it some way or the other so the requests to Django are always authenticated when the user is logged in. This does not seem to be the case right now.

**Comment by agger-magenta** [comment]
It's actually very easy to require authentication on views. I committed a very small demonstration, requiring authentication on `mucua_list` (commented out!), mainly chosen because it's very easy to test with `curl`. The tricky part though is that all calls to the API in the client must supply credentials if the user is logged in. I'll try and see if there's some easy way I can do that.

**Comment by agger-magenta** [comment]
Anyway, I'll start introducing all the authentication on a separate branch tomorrow & then we can se how to introduce authentication on the client side.

**Comment by agger-magenta** [comment]
Authentication is now required on all API calls which change data. Works fine in the existing user interface. Pushed to master.

Next in line: More fine-grained permissions, e.g. prevent mocambolas from deleting media from a different mucua.

**Comment by agger-magenta** [comment]
As Vince pointed out, this doesn't really work, as the API is not authenticating.

The best/fastest way of implementing this would probably be to use basic HTTTP authentication, which is supported by Django. This involves setting an "Authorization" header as described here:

http://restcookbook.com/Basics/loggingin/

Fernão: What would it involve to supply this header in all calls for logged-in users? Do you think it would be difficult? It's probably better than using session-based auth since RESTful APIs should be stateless.

**Comment by fernao** [comment]
Hi! I'll study this in order to improve authentication. Actually, the authentication is a simple check of user/password that creates a cookie on client side.

**Comment by agger-magenta** [comment]
Thanks! This same check could easily generate a base64-encoding of username:password and send this token in the Authorization HTTP header of subsequent API calls, until the user logs out. This would be immediately supported by Django-REST via its BasicAuth method.

**Comment by agger-magenta** [comment]
The authentication & permissions check is still present on the "permissions" branch.

I can also look at it, but in that case I'd like a pointer to which files should be modified in order to send the header correctly. I don't have an overview of the client yet. :)

**Comment by fernao** [comment]
Now I got it... token is a modern way that replaces cookies for authentication, and also removes the need of using csrf, and many other advantages. Maybe I'll have to work on it on another branch too.

Some docs for reference:
https://raibledesigns.com/rd/entry/implementing_ajax_authentication_using_jquery
https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/
http://stackoverflow.com/questions/5288150/digest-authentication-w-jquery-is-it-possible

**Comment by fernao** [comment]
Hi Agger!

I've started implementing token auth and other things, but I'm stuck on correctly generating the authentication token. I've tried jwt (Json Web Token), but it didn't worked as I supposed. I think I need to generate then according to your authentication effort.

You can check it at 'permissions' branch...

**Comment by agger-magenta** [comment]
Hi Fernão

I'll have a look!
But the token for BasicAuth (which is where I suggest we start) is really very simple, it's just a base64 encoding of username:password which is to be put in the Authentication: header. But as said, I'll have a look at it!

**Comment by agger-magenta** [comment]
... but of course you know that, having implemented it ... I'll see if I can figure out what goes wrong.

**Comment by agger-magenta** [comment]
What you're doing, taking the token from sessionStorage, looks correct; I haven't checked the value of the token yet, though. I suggested BasicAuth, but the django-rest documentation states that " Basic authentication is generally only appropriate for testing." So I suppose not.

I'll just try a few things out. Worst case, we'll have to write our own middleware to do this, but I think not.

**Comment by agger-magenta** [comment]
I've been looking around & ended up returning to django-rest.

There's a number of packages that support a more secure auth than Basic or Token, e.g. OAuth and HTTP Digest: http://www.django-rest-framework.org/api-guide/authentication/#third-party-packages

I think I'll play around with some of them tomorrow to see which seems to work best. It'll also be nice to avoid sending the password in plaintext for each API request.

**Comment by agger-magenta** [comment]
I committed a first implementation of genrating a Basic Auth token on the permissions branch, but didn't test it yet. I think first step *could* be to get basic auth running, then switching to one of the more secure ones.

**Comment by fernao** [comment]
Hi there, I've tested it here, but it's requiring the header even at login page, so the user cannot generate his token.

**Comment by agger-magenta** [comment]
I'll look into it.

Currently, the login and create_auth views in the mocambola class aren't 
requiring authentication, so they should work without the token.

Only views decorated with 
@authentication_classes((SessionAuthentication, BasicAuthentication)) 
should be expecting the token.

On 06/24/2015 03:28 PM, fernao wrote:
>
> Hi there, I've tested it here, but it's requiring the header even at 
> login page, so the user cannot generate his token.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/RedeMocambos/baobaxia/issues/162#issuecomment-114867536>.
>

-- 
Carsten Agger
Magenta ApS
Incuba, Åbogade 15
DK-8200 Aarhus N

Tlf +45 3336 9699
Dir +45 5060 1476
Mob +45 2086 5010

http://www.magenta.dk
carstena@magenta.dk

**Comment by fernao** [comment]
Login page calls "/api/mocambos/mucuas", to get the list of mucuas that 
user can authenticate.

I've checked, and 'mucua_list' method is not decorated with 
@authentication_classes...

weird!


Em 2015-06-24 10:35, Carsten Agger escreveu:

**Comment by agger-magenta** [comment]
Well, I just found part of the explanation:

There was a bug in the __prepareLoginData function I created, a variable 
got the wrong name.

I've debugged in Firebug, and the token seems to be generated correctly 
(commit 4c47ce061a6d533b449ae30814dd8312d5fcd398).

However, the __checkLogin function, where the token is set in 
localStorage, is apparently never called. That might explain  it?


But I can't just figure why. Will continue looking ...

**Comment by agger-magenta** [comment]
With this commit:

8d43a654bf4b7a3fc0edfcde86db00d9ebf9e26a

the token is set in sessionStorage and in main.js the header seems to be 
sent correctly.

It's difficult to verify though, because even though the $.post call 
seems to log the user in correctly, the login page is not redirecting 
properly.

But the actual generation and passing of the token ought to work (for 
BasicAuth).

**Comment by fernao** [comment]
I've tried, and it worked, for updating content too.

But as you've set the token directly on prepareLogin(), the result is got before running checkLogin() - that verify at server if user exists, passwords match etc. This raised an error because token session is set even if user is not allowed.

**Comment by fernao** [comment]
Last commit fixed that, check it out, seems to be working =)

**Comment by agger-magenta** [comment]
Cool! Unfortunately I'm getting som errors, a syntex error and a call to
checkLogin() which doesn't exist anymore. Do you know what goes wrong? I
tried to fix it but didn't really have any luck with it.

2015-06-24 17:47 GMT+02:00 fernao <notifications@github.com>:

> Last commit fixed that, check it out, seems to be working =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/RedeMocambos/baobaxia/issues/162#issuecomment-114920657>
> .
>



-- 
Carsten Agger
Magenta ApS
Åbogade 15
8200 Århus N

Tlf  +45 2086 5010
http://www.magenta-aps.dk
carstena@magenta-aps.dk

**Comment by fernao** [comment]
I think it's cache!

try to ctrl + shift + r, or clear all cache of the browser. Also, maybe 
you need to clean sessionStorage and localStorage at javascript console:

sessionStorage.clear();
localStorage.clear();


Em 2015-06-24 16:13, Carsten Agger escreveu:

**Comment by fernao** [comment]
woops, I've found that.

**Comment by agger-magenta** [comment]
Yes, I've now tested it and it's working on hyndla! 

As it is now, getting the token from the server, I think it will also work if we switch to using the JWT token you did the groundwork for.

**Comment by agger-magenta** [comment]
I think we're getting there with this one.
I've removed the support for BasicAuth and made the JavaScript use the JWT authentication instead.
I've also merged master into permissions to make sure there are no conflicts. This is currently running on hyndla and seems to work fine.

If you could test it too, I think we're approaching the point where we can merge this to master.

**Comment by fernao** [comment]
cool!

I think we need to add jwt library at PIP, so new installs automatically 
get this installed.

The led us to the improvement of upgrade tasks, that we can look at on 
the next days.


Em 2015-06-27 12:15, Carsten Agger escreveu:

**Comment by fernao** [comment]
Media publishing & gallery still buggy; GET requests are ok, but POST not. I'm working on it.

**Comment by fernao** [comment]
I've fixed redirection and POST requests, now all of then have Authentication headers set.

**Comment by fernao** [comment]
When looking at media/[uuid] (media view) and logged in, got an 403 error with following message:
{"detail": "Signature has expired."}

But couldn't reproduce it again...

**Comment by fernao** [comment]
Bug: when user log into api/admin in paralel with navigating on interface: at interface, raises a csrf error, because API creates two cookies (csrf and session). Logout of api/admin stop the error.

**Comment by fernao** [comment]
I think that code is ok to go to master, so if we got any error we handle at that branch.

**Comment by agger-magenta** [comment]
That's great news! :-)

Though: Login to the backend via session cookie shouldn't interact with the front-end token-based login, so ideally it should work either way. However, I agree that's probably not so important if the rest is working.

**Comment by agger-magenta** [comment]
On hyndla, after updating master & restarting gunicorn+update-templates, new gallery function fails with HTTP 500 for the file uploads.

I get this in the gunicorn log:

```
Internal Server Error: /api/mocambos/hyndla/media/
Traceback (most recent call last):
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/rest_framework/views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/srv/bbx/baobaxia/app/django-bbx/media/views.py", line 416, in media_detail
    if request.DATA['author'] != '':
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/srv/bbx/envs/bbx/local/lib/python2.7/site-packages/django/db/models/query.py", line 310, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
```
When uploading  single file, it apparently succeeds "100%", then stops with the same error. Also, Firebug complains about a syntax error:
```

SyntaxError: missing ) in parenthetical
	

(DoesNotExist at /api/mocambos/hyndla/media/

	
MediaPublish.js (line 1, col 14)
```
I don't have time to pursue this right now, but if it works on other mucuas I may have done something wrong during the update.
